{% set name = "pytest-astropy-header" %}
{% set version = "0.2.2" %}
{% set git_url = "https://github.com/astropy/pytest-astropy-header" %}
{% set sha256 = "77891101c94b75a8ca305453b879b318ab6001b370df02be2c0b6d1bb322db10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pytest >=4.6
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - pytest >=4.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_astropy_header
    - pytest_astropy_header.display

about:
  home: {{ git_url }}
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Pytest plugin to add diagnostic information to the header of the test output
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - mwcraig
    - astrofrog
    - bsipocz
