{% set name = "pytest-astropy-header" %}
{% set version = "0.2.0" %}
{% set git_url = "https://github.com/astropy/pytest-astropy-header" %}
{% set sha256 = "50d60c92d988510e7bceade795a79ed143b36fd70b17fd1bfa778eb428a4a166" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - pytest >=3.0
  run:
    - python
    - pytest >=3.0

test:
  imports:
    - pytest_astropy_header
    - pytest_astropy_header.display

about:
  home: {{ git_url }}
  license_family: BSD
  license: BSD 3-Clause
  license_file: LICENSE.rst
  summary: Pytest plugin to add diagnostic information to the header of the test output
  doc_url: {{ git_url }}
  dev_url: {{ git_url }}

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - bsipocz
